name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Build With Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build Result for ${{ github.repository }}"
          description: |
            ${{ job.status != 'success' && format('Failure at stage: {0}', job.status) || 'Build succeeded!' }}
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
